# Generated by Django 5.0.4 on 2024-07-05 05:47

import django.db.models.deletion
import dressapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=dressapp.models.getFileName
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vendor", models.CharField(max_length=100)),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=dressapp.models.getFileName
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("Market_price", models.FloatField()),
                ("Customer_price", models.FloatField()),
                ("Dealer_price", models.FloatField()),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0-default,1-Trending"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catagory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dressapp.catagory",
                    ),
                ),
            ],
        ),
    ]
